services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb
